import { Inter } from "next/font/google";
import "./globals.css";
import AddTask from "@/Component/AddTask/AddTask";
import ListTask from "@/ListTask/ListTask";
import { provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <provider>
          <AddTask />
          {children}
          <ListTask />
        </provider>
      </body>
    </html>
  );
}
